language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - cd Client 
  - npm install
script:
  - ng lint
  - ng build --prod --base-href https://pawel095.github.io/Pedzace-Zolwie/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: Client/dist
  on:
    branch: master

